#!/bin/sh

set -e

BASEPATH="$HOME/.zeta_shell"

if [ -e $BASEPATH/.git ]; then
    cd $BASEPATH && git pull
else
    git clone https://github.com/gekorob/zetashell.git $BASEPATH
fi

curl -fsSL https://raw.githubusercontent.com/robbyrussell/oh-my-zsh/master/tools/install.sh | sh

ln -sf $BASEPATH/zshrc ~/.zshrc
ln -sf $BASEPATH/aliases ~/.zsh_aliases

chsh -s $(which zsh)
